#!/bin/bash

# ==============================================================================
# Biet Network - Base Sepolia Testnet Deployment Script
# ==============================================================================

set -e

echo "🚀 Biet Network - Base Sepolia Testnet Deployment"
echo "=================================================="

# Check if .env file exists
if [ ! -f .env ]; then
    echo "❌ .env file not found!"
    echo "Please copy .env.example to .env and fill in your values:"
    echo "cp .env.example .env"
    exit 1
fi

# Load environment variables
source .env

# Check required variables
if [ -z "$PRIVATE_KEY" ]; then
    echo "❌ PRIVATE_KEY not found in .env file"
    exit 1
fi

if [ -z "$BASE_SEPOLIA_RPC_URL" ]; then
    echo "❌ BASE_SEPOLIA_RPC_URL not found in .env file"
    exit 1
fi

echo "📋 Configuration Check:"
echo "✅ .env file found"
echo "✅ PRIVATE_KEY configured"
echo "✅ BASE_SEPOLIA_RPC_URL configured"

# Check wallet balance
echo ""
echo "💰 Checking wallet balance..."
WALLET_ADDRESS=$(cast wallet address --private-key $PRIVATE_KEY)
echo "📍 Wallet address: $WALLET_ADDRESS"

BALANCE=$(cast balance $WALLET_ADDRESS --rpc-url $BASE_SEPOLIA_RPC_URL)
echo "💵 Balance: $BALANCE ETH"

# Convert balance to wei for check
BALANCE_WEI=$(cast to-wei $BALANCE)
MIN_BALANCE=$(cast to-wei 0.01)

if [ "$BALANCE_WEI" -lt "$MIN_BALANCE" ]; then
    echo "⚠️  Warning: Low balance! Get test ETH from https://sepoliafaucet.com/"
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo ""
echo "🔨 Starting deployment..."
echo "Network: Base Sepolia"
echo "RPC: $BASE_SEPOLIA_RPC_URL"

# Run deployment
if [ -n "$BASESCAN_API_KEY" ]; then
    echo "🔍 Verifying contracts on BaseScan..."
    forge script script/Deploy.s.sol:DeployTestnetScript \
        --rpc-url $BASE_SEPOLIA_RPC_URL \
        --broadcast \
        --verify \
        --verifier-url https://api-sepolia.basescan.org/api \
        --etherscan-api-key $BASESCAN_API_KEY || true
else
    echo "⚠️  Skipping verification (no BASESCAN_API_KEY found)"
    echo "🔨 Deploying contracts..."
    forge script script/Deploy.s.sol:DeployTestnetScript \
        --rpc-url $BASE_SEPOLIA_RPC_URL \
        --broadcast || true
fi

echo ""
echo "✅ Deployment completed!"
echo ""
echo "📊 Next steps:"
echo "1. Check the deployed addresses above"
echo "2. Update your .env file with the deployed addresses"
echo "3. Verify on BaseScan: https://sepolia.basescan.org/"
echo "4. Test the contracts using the deployed addresses"

# ------------------------------------------------------------------------------
# Write deployment addresses to file (requires jq)
# ------------------------------------------------------------------------------

# Foundry writes the latest broadcast for this script under this path on Base
# Sepolia (chain id 84532).
BROADCAST_FILE="broadcast/Deploy.s.sol/84532/run-latest.json"

if command -v jq >/dev/null 2>&1 && [ -f "$BROADCAST_FILE" ]; then
    echo "" 
    echo "📝 Extracting contract addresses from $BROADCAST_FILE"

    BGT_TOKEN=$(jq -r '.transactions[] | select(.contractName=="BGT") | .contractAddress' "$BROADCAST_FILE" | tail -n1)
    TIMELOCK=$(jq -r '.transactions[] | select(.contractName=="TimelockController") | .contractAddress' "$BROADCAST_FILE" | tail -n1)
    DAO=$(jq -r '.transactions[] | select(.contractName=="BGTDAO") | .contractAddress' "$BROADCAST_FILE" | tail -n1)
    TREASURY=$(jq -r '.transactions[] | select(.contractName=="BGTTreasury") | .contractAddress' "$BROADCAST_FILE" | tail -n1)
    IDENTITY=$(jq -r '.transactions[] | select(.contractName=="BietIdentity") | .contractAddress' "$BROADCAST_FILE" | tail -n1)
    PRODUCTIVE_UNIT=$(jq -r '.transactions[] | select(.contractName=="ProductiveUnit") | .contractAddress' "$BROADCAST_FILE" | tail -n1)
    REVENUE_SHARE=$(jq -r '.transactions[] | select(.contractName=="RevenueShare") | .contractAddress' "$BROADCAST_FILE" | tail -n1)
    BGT_SALE=$(jq -r '.transactions[] | select(.contractName=="BGTSale") | .contractAddress' "$BROADCAST_FILE" | tail -n1)

    mkdir -p deployments

    ENV_OUT="deployments/base-sepolia-latest.env"
    LOG_OUT="deployments/base-sepolia-history.log"

    {
        echo "# Generated by deploy-testnet.sh on $(date -u)"
        echo "NEXT_PUBLIC_BGT_TOKEN_ADDRESS=$BGT_TOKEN"
        echo "NEXT_PUBLIC_TIMELOCK_ADDRESS=$TIMELOCK"
        echo "NEXT_PUBLIC_DAO_ADDRESS=$DAO"
        echo "NEXT_PUBLIC_TREASURY_ADDRESS=$TREASURY"
        echo "NEXT_PUBLIC_BIET_IDENTITY_ADDRESS=$IDENTITY"
        echo "NEXT_PUBLIC_PRODUCTIVE_UNIT_ADDRESS=$PRODUCTIVE_UNIT"
        echo "NEXT_PUBLIC_REVENUE_SHARE_ADDRESS=$REVENUE_SHARE"
        echo "NEXT_PUBLIC_BGT_SALE_ADDRESS=$BGT_SALE"
    } > "$ENV_OUT"

    {
        echo "--- $(date -u) ---"
        cat "$ENV_OUT"
        echo ""
    } >> "$LOG_OUT"

    echo ""
    echo "✅ Wrote latest Base Sepolia addresses to $ENV_OUT"
    echo "📚 Deployment history appended to $LOG_OUT"
else
    echo ""
    echo "⚠️  Skipping address file generation: jq not found or no broadcast file at $BROADCAST_FILE"
fi
echo ""
echo "📚 For more help, see DEPLOYMENT_GUIDE.md"
